### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/englishlanguageinstitute#11]
Create main admin panel that should insert student and all other entities

**Comment by Hazrat-Bilal** [comment]
done it...

**Comment by mjks4545** [comment]
Tasks for tomorrow is that create edit delete in all the create views and also create a view to view all the visitors like in the form table... we will try to rap up application section too....

**Comment by mjks4545** [comment]
also create a table for roles like admin reciption etc

**Comment by Hazrat-Bilal** [comment]
Previous task is done.....but roles are still in pending

**Comment by mjks4545** [comment]
some small work left we are not yet sure
