### ISSUE TITLE
Gender

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/englishlanguageinstitute#39]
Add gender field to both teacher and student submission from..

**Comment by mjks4545** [comment]
merge other staff and teacher make it staff
missing fields
Gender-Done
job designation -done
job specification-done
tenoure of contract-done
increment-done
security ratio-done
job `hours-done
<span class="fa fa-male"></span>

**Comment by mjks4545** [comment]
teacher salary slip auto generation after each month on the base of attandance

**Comment by muhammadullah293** [comment]
field done,inserted success.and now retrieving is in progress :+1:

**Comment by mjks4545** [comment]
create a filed in teacher by the name of posting

**Comment by mjks4545** [comment]
create a filed in teacher by the name of branch
