### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by mjks4545** [mjks4545/englishlanguageinstitute#6]
![imag0166](https://cloud.githubusercontent.com/assets/15276763/14224720/ec243c68-f8bf-11e5-9c1b-3c9f59cb9134.jpg)
![imag0167](https://cloud.githubusercontent.com/assets/15276763/14224721/eff00b2e-f8bf-11e5-8771-e43e3c187afa.jpg)

**Comment by Hazrat-Bilal** [comment]
View for all apps are done....now start to make it dynamic

**Comment by mjks4545** [comment]
Create is being completed
